import fs from "node:fs";
import path from "node:path";

import { isRepoTrusted } from "../trust-allowlist.mjs";
import { matchesGlob } from "../spec-harness-lib.mjs";
import { QUALITY_ADAPTERS, getQualityAdapter } from "./adapters/registry.mjs";
import { capabilityInProfile, capabilityRules } from "./adapters/shared.mjs";
import { listRepositoryFiles, matchesPathScope } from "./paths.mjs";

function applyExclusions(repoRoot, files, patterns, paths = []) {
  const counts = new Map();
  const included = [];
  for (const file of files) {
    // The path filter runs first so an out-of-scope file is attributed to the
    // filter rather than to a policy pattern, and so it skips the per-file
    // generated-marker read below.
    let reason = paths.length > 0 && !matchesPathScope(paths, file) ? "outside path filter" : undefined;
    if (!reason) {
      const pattern = patterns.find((candidate) => matchesGlob(candidate, file));
      reason = pattern ? `policy pattern ${pattern}` : undefined;
    }
    if (!reason) {
      try {
        const firstLines = fs.readFileSync(path.join(repoRoot, file), "utf8").split("\n").slice(0, 3).join("\n");
        if (/Code generated .* DO NOT EDIT|@generated|Autogenerated by/i.test(firstLines)) reason = "generated marker";
      } catch {}
    }
    if (reason) counts.set(reason, (counts.get(reason) ?? 0) + 1);
    else included.push(file);
  }
  return { files: included, exclusions: [...counts.entries()].map(([reason, count]) => ({ reason, count })).sort((a, b) => a.reason.localeCompare(b.reason)) };
}

function under(file, root) { return root === "." || file === root || file.startsWith(`${root}/`); }
function nearestRoot(file, components, language) {
  return components.filter((component) => component.language === language && under(file, component.root)).sort((a, b) => b.root.length - a.root.length)[0];
}

function readTsOptions(repoRoot, marker) {
  try {
    const text = fs.readFileSync(path.join(repoRoot, marker), "utf8").replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
    return JSON.parse(text).compilerOptions ?? {};
  } catch { return {}; }
}

function hasTsCheck(repoRoot, file) {
  try {
    return /(?:^|\n)\s*\/\/\s*@ts-check\b/.test(fs.readFileSync(path.join(repoRoot, file), "utf8").split("\n").slice(0, 5).join("\n"));
  } catch {
    return false;
  }
}

/** Detect language components and non-executing capability plans. */
export function detectQualityCapabilities({ repoRoot, policy = {}, paths = [] } = {}) {
  const filtered = applyExclusions(repoRoot, listRepositoryFiles(repoRoot), policy.exclude ?? [], paths);
  const files = filtered.files;
  const discovered = QUALITY_ADAPTERS.flatMap((adapter) => adapter.discover({ root: repoRoot, files }));
  const byKey = new Map();
  for (const item of discovered) {
    const key = `${path.posix.normalize(item.root)}:${item.language}`;
    const previous = byKey.get(key);
    byKey.set(key, {
      ...previous,
      ...item,
      markers: [...new Set([...(previous?.markers ?? []), ...(item.markers ?? [])])].sort((a, b) => {
        const preferred = (marker) => path.basename(marker) === "tsconfig.json" ? 0 : 1;
        return preferred(a) - preferred(b) || a.localeCompare(b);
      }),
    });
  }
  for (const configured of policy.components ?? []) {
    const root = path.posix.normalize(configured.root);
    for (const language of configured.languages) {
      const key = `${root}:${language}`;
      // `configured` records provenance: the operator declared this component,
      // which is a stronger claim on the repository than any discovered marker.
      // Adapters use it to tell a hand-declared root from one inferred out of
      // stray source files (make-tools.mjs).
      byKey.set(key, { ...(byKey.get(key) ?? { root, language, markers: [] }), configured: true, tools: configured.tools ?? {} });
    }
  }
  const components = [...byKey.values()].map((component) => ({
    ...component,
    id: `${component.root}:${component.language}`,
    absoluteRoot: path.resolve(repoRoot, component.root),
    files: files.filter((file) => under(file, component.root)),
    state: (getQualityAdapter(component.language) || Object.values(component.tools ?? {}).some((tool) => ["exit-code", "dotbabel-v1"].includes(tool.report?.format ?? "exit-code"))) ? "checked" : "unsupported",
    evidence: component.markers,
  }));
  const tsComponents = components.filter((component) => component.language === "typescript");
  for (const component of tsComponents) {
    const options = readTsOptions(repoRoot, component.markers[0]);
    const ownsJs = options.allowJs === true || options.checkJs === true;
    const ownedJavaScript = component.files.filter((file) => /\.[cm]?js$/.test(file) && (ownsJs || hasTsCheck(repoRoot, file)));
    component.files = component.files.filter((file) => !/\.[cm]?js$/.test(file) || ownedJavaScript.includes(file));
    for (const js of components.filter((item) => item.language === "javascript" && item.root === component.root)) {
      js.files = js.files.filter((file) => !ownedJavaScript.includes(file));
    }
  }
  for (const component of components) {
    component.files = component.files.filter((file) => nearestRoot(file, components, component.language)?.id === component.id);
  }
  components.sort((a, b) => a.id.localeCompare(b.id));
  const trust = isRepoTrusted({ repoRoot });
  return { repoRoot, files, components, trust, exclusions: filtered.exclusions, rejectedCandidates: [], paths };
}

/** Create adapter plans for a detected repository. */
export function planQualityCheck({ repoRoot, policy, changeSet, profile, detection, paths = [] } = {}) {
  const found = detection ?? detectQualityCapabilities({ repoRoot, policy, paths });
  const plans = found.components.flatMap((component) => getQualityAdapter(component.language)?.plan(component, policy, changeSet, profile) ?? genericPlans(component, profile));
  // A path filter turns a reporting narrowing into an execution narrowing: a
  // component with no in-scope file must not run its package-level tools.
  // Guarded, because a component can hold no file in an unfiltered run.
  const scoped = paths.length === 0 ? plans : plans.filter((plan) => (found.components.find((component) => component.id === plan.componentId)?.files.length ?? 0) > 0);
  return { ...found, plans: scoped };
}

function genericPlans(component, profile) {
  return Object.entries(component.tools ?? {}).filter(([capability]) => capabilityInProfile(capability, profile)).map(([capability, tool]) => ({ id: `${component.id}:${capability}`, componentId: component.id, capability, ruleIds: capabilityRules(capability), executable: tool.argv[0], argv: tool.argv.slice(1), cwd: component.absoluteRoot, timeoutSeconds: tool.timeout_seconds, report: tool.report, availability: "available", source: "project", requiresTrust: true }));
}
